# Generated by Django 5.2.13 on 2026-04-07 17:08

import django.db.models.deletion
from django.db import migrations, models


def _create_book_embeddings_initial(apps, schema_editor):
    """book_embeddings 초기 생성 — PostgreSQL + pgvector 환경에서만."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE TABLE IF NOT EXISTS book_embeddings (
            id          BIGSERIAL PRIMARY KEY,
            book_id     INTEGER NOT NULL UNIQUE REFERENCES books(id) ON DELETE CASCADE,
            embedding   vector(1024),
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    """)
    schema_editor.execute("""
        CREATE INDEX IF NOT EXISTS book_embeddings_hnsw_idx
            ON book_embeddings USING hnsw (embedding vector_cosine_ops);
    """)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '도서 임베딩',
                'verbose_name_plural': '도서 임베딩',
                'db_table': 'book_embeddings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='저자명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '저자',
                'verbose_name_plural': '저자',
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(help_text='D-246 형식', max_length=20, unique=True, verbose_name='도서 코드')),
                ('title', models.CharField(max_length=500, verbose_name='도서명')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='썸네일 URL')),
                ('description', models.TextField(blank=True, verbose_name='도서 소개')),
                ('difficulty', models.CharField(blank=True, choices=[('입문', '입문'), ('초급', '초급'), ('중급', '중급'), ('고급', '고급')], max_length=10, verbose_name='난이도')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='출판일')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='페이지 수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서',
                'db_table': 'books',
                'ordering': ['book_code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='출판사명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '출판사',
                'verbose_name_plural': '출판사',
                'db_table': 'publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveSmallIntegerField(default=1, verbose_name='저자 순서')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': '도서-저자',
                'verbose_name_plural': '도서-저자',
                'db_table': 'book_authors',
                'ordering': ['author_order'],
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='books.BookAuthor', to='books.author', verbose_name='저자'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.category')),
            ],
            options={
                'verbose_name': '도서-카테고리',
                'verbose_name_plural': '도서-카테고리',
                'db_table': 'book_categories',
                'unique_together': {('book', 'category')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', through='books.BookCategory', to='books.category', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.publisher', verbose_name='출판사'),
        ),
        migrations.RunPython(
            _create_book_embeddings_initial,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
