# Generated by Django 5.2.15 on 2026-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_rename_yes24candidate_to_kyobocandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='source_url',
            field=models.URLField(blank=True, help_text='교보문고 등 도서 정보를 수집한 원본 링크', max_length=1000, verbose_name='수집 출처 URL'),
        ),
    ]
