# Generated by Django 5.2.13 on 2026-04-07 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '챗봇 세션',
                'verbose_name_plural': '챗봇 세션',
                'db_table': 'chat_sessions',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI')], max_length=20, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('question_type', models.CharField(blank=True, choices=[('roadmap', '학습 로드맵'), ('level_based', '수준별 추천'), ('general', '일반 도서 질문'), ('unrelated', '도서 무관')], help_text='assistant 메시지에만 설정', max_length=20, verbose_name='질문 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '챗봇 메시지',
                'verbose_name_plural': '챗봇 메시지',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(verbose_name='유사도 점수')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='추천 순위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='books.book', verbose_name='도서')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chat.chatmessage', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '추천 도서',
                'verbose_name_plural': '추천 도서',
                'db_table': 'chat_recommendations',
                'ordering': ['rank'],
                'unique_together': {('message', 'book')},
            },
        ),
    ]
