# Generated by Django 5.2.15 on 2026-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='question_type',
            field=models.CharField(blank=True, choices=[('keyword_search', '도서 목록 조회'), ('specific_search', '특정 기술·키워드 탐색'), ('goal_oriented', '진로·목적 큐레이션'), ('career_certification', '자격증·포트폴리오'), ('level_based', '수준별 추천'), ('out_of_scope', '도서 무관')], help_text='assistant 메시지에만 설정', max_length=20, verbose_name='질문 유형'),
        ),
    ]
